//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.LessonStudents = new HashSet<LessonStudent>();
        }
    
        public int ID { get; set; }
        public int ID_Subject { get; set; }
        public System.DateTime DataLesson { get; set; }
        public int ID_Teacher { get; set; }
        public int ID_Group { get; set; }
        public int NumberOfHours { get; set; }
        public string TypeLesson { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> MaxPoint { get; set; }
    
        public virtual CuratorOrTeacher CuratorOrTeacher { get; set; }
        public virtual Group Group { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonStudent> LessonStudents { get; set; }
    }
}
